### ISSUE TITLE
Pixelization extension breaks launch options

### ISSUE THREAD

**Issue by Sibune** [filipemeneses/comfy_pixelization#1]
Launch options such as --preview-method or --listen cause ComfyUI to error on launch while this extension is installed.

Related issue: https://github.com/comfyanonymous/ComfyUI/issues/781#issue-1766353463

**Comment by filipemeneses** [comment]
Thanks for reporting! f8e4fe6 should fix the issue.

The thing happens with ComfyUI_tagger, I opened an issue there too: https://github.com/gamert/ComfyUI_tagger/issues/4
One alternative for ComfyUI_tagger is https://github.com/pythongosssss/ComfyUI-Custom-Scripts WD14 Tagger
