### ISSUE TITLE
Pixelation node should not be set as OUTPUT_NODE=True

### ISSUE THREAD

**Issue by SirVeggie** [filipemeneses/comfy_pixelization#10]
The pixelation node is not an output node, the `OUTPUT_NODE=True` setting will cause the node to execute even when it is in an inactive branch. Removing the line is enough to fix the issue, and does not affect the functionality of the node.

I already fixed it in local but this requires modifying the code each time the extension is installed, so removing that line would be a great help, thanks!

**Comment by filipemeneses** [comment]
Thanks for sharing! fixed with 3009868fc33c8d5ff7e418631fd3ce1ee492d8a5
